[project]
name = 'fusion-router'

[install]
tools = true

[commands]
build = 'rojo build default.project.json --output build.rbxl'
dev = 'rojo serve default.project.json'
format = 'stylua src'
lint = 'selene src'
test = 'lune run test'

[tasks]
install = ['cd packages/fusion-router && luu install', 'luu install']