[project]
name = 'fusion-router'

[install]
tools = true

[commands]
build = 'rojo build default.project.json --output build.rbxl'
dev = 'rojo serve default.project.json'
format = 'stylua packages/fusion-router/src packages/fusion-router/test test.luau'
lint = 'selene packages/fusion-router/src packages/fusion-router/test test.luau'
test = 'lune run test'

[tasks]
install = ['cd packages/fusion-router && luu install', 'luu install']
